**Importing the libraries**

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.preprocessing import MinMaxScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.model_selection import train_test_split
import pickle

load your datset

In [2]:
df=pd.read_csv('/content/hypothyroid.csv')
df.head()

,age,sex,on thyroxine,query on thyroxine,on antithyroid medication,sick,pregnant,thyroid surgery,I131 treatment,query hypothyroid,...,TT4 measured,TT4,T4U measured,T4U,FTI measured,FTI,TBG measured,TBG,referral source,binaryClass
0,41,F,f,f,f,f,f,f,f,f,...,t,125,t,1.14,t,109,f,?,SVHC,P
1,23,F,f,f,f,f,f,f,f,f,...,t,102,f,?,f,?,f,?,other,P
2,46,M,f,f,f,f,f,f,f,f,...,t,109,t,0.91,t,120,f,?,other,P
3,70,F,t,f,f,f,f,f,f,f,...,t,175,f,?,f,?,f,?,other,P
4,70,F,f,f,f,f,f,f,f,f,...,t,61,t,0.87,t,70,f,?,SVI,P

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3772 entries, 0 to 3771
Data columns (total 30 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   age                        3772 non-null   object
 1   sex                        3772 non-null   object
 2   on thyroxine               3772 non-null   object
 3   query on thyroxine         3772 non-null   object
 4   on antithyroid medication  3772 non-null   object
 5   sick                       3772 non-null   object
 6   pregnant                   3772 non-null   object
 7   thyroid surgery            3772 non-null   object
 8   I131 treatment             3772 non-null   object
 9   query hypothyroid          3772 non-null   object
 10  query hyperthyroid         3772 non-null   object
 11  lithium                    3772 non-null   object
 12  goitre                     3772 non-null   object
 13  tumor                      3772 non-null   object
 14  hypopituitary              3772 non-null   object
 15  psych                      3772 non-null   object
 16  TSH measured               3772 non-null   object
 17  TSH                        3772 non-null   object
 18  T3 measured                3772 non-null   object
 19  T3                         3772 non-null   object
 20  TT4 measured               3772 non-null   object
 21  TT4                        3772 non-null   object
 22  T4U measured               3772 non-null   object
 23  T4U                        3772 non-null   object
 24  FTI measured               3772 non-null   object
 25  FTI                        3772 non-null   object
 26  TBG measured               3772 non-null   object
 27  TBG                        3772 non-null   object
 28  referral source            3772 non-null   object
 29  binaryClass                3772 non-null   object
dtypes: object(30)
memory usage: 884.2+ KB

In [4]:
df.shape

(3772, 30)

In [5]:
le=LabelEncoder()
for x in df.columns:
    df[x]=le.fit_transform(df[x])
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3772 entries, 0 to 3771
Data columns (total 30 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   age                        3772 non-null   int64
 1   sex                        3772 non-null   int64
 2   on thyroxine               3772 non-null   int64
 3   query on thyroxine         3772 non-null   int64
 4   on antithyroid medication  3772 non-null   int64
 5   sick                       3772 non-null   int64
 6   pregnant                   3772 non-null   int64
 7   thyroid surgery            3772 non-null   int64
 8   I131 treatment             3772 non-null   int64
 9   query hypothyroid          3772 non-null   int64
 10  query hyperthyroid         3772 non-null   int64
 11  lithium                    3772 non-null   int64
 12  goitre                     3772 non-null   int64
 13  tumor                      3772 non-null   int64
 14  hypopituitary              3772 non-null   int64
 15  psych                      3772 non-null   int64
 16  TSH measured               3772 non-null   int64
 17  TSH                        3772 non-null   int64
 18  T3 measured                3772 non-null   int64
 19  T3                         3772 non-null   int64
 20  TT4 measured               3772 non-null   int64
 21  TT4                        3772 non-null   int64
 22  T4U measured               3772 non-null   int64
 23  T4U                        3772 non-null   int64
 24  FTI measured               3772 non-null   int64
 25  FTI                        3772 non-null   int64
 26  TBG measured               3772 non-null   int64
 27  TBG                        3772 non-null   int64
 28  referral source            3772 non-null   int64
 29  binaryClass                3772 non-null   int64
dtypes: int64(30)
memory usage: 884.2 KB

In [6]:
df.isnull().sum()

age                          0
sex                          0
on thyroxine                 0
query on thyroxine           0
on antithyroid medication    0
sick                         0
pregnant                     0
thyroid surgery              0
I131 treatment               0
query hypothyroid            0
query hyperthyroid           0
lithium                      0
goitre                       0
tumor                        0
hypopituitary                0
psych                        0
TSH measured                 0
TSH                          0
T3 measured                  0
T3                           0
TT4 measured                 0
TT4                          0
T4U measured                 0
T4U                          0
FTI measured                 0
FTI                          0
TBG measured                 0
TBG                          0
referral source              0
binaryClass                  0
dtype: int64

In [7]:
df.head()

,age,sex,on thyroxine,query on thyroxine,on antithyroid medication,sick,pregnant,thyroid surgery,I131 treatment,query hypothyroid,...,TT4 measured,TT4,T4U measured,T4U,FTI measured,FTI,TBG measured,TBG,referral source,binaryClass
0,34,1,0,0,0,0,0,0,0,0,...,1,28,1,72,1,10,0,0,1,1
1,15,1,0,0,0,0,0,0,0,0,...,1,3,0,146,0,234,0,0,4,1
2,40,2,0,0,0,0,0,0,0,0,...,1,10,1,48,1,22,0,0,4,1
3,67,1,1,0,0,0,0,0,0,0,...,1,83,0,146,0,234,0,0,4,1
4,67,1,0,0,0,0,0,0,0,0,...,1,201,1,44,1,199,0,0,3,1

In [8]:
# for standard scaler
from sklearn.preprocessing import MinMaxScaler
norm = MinMaxScaler().fit(df)

# Transform the  data
norm_data = norm.transform(df)
scaled_df = pd.DataFrame(norm_data, columns=df.columns)
scaled_df.head()

,age,sex,on thyroxine,query on thyroxine,on antithyroid medication,sick,pregnant,thyroid surgery,I131 treatment,query hypothyroid,...,TT4 measured,TT4,T4U measured,T4U,FTI measured,FTI,TBG measured,TBG,referral source,binaryClass
0,0.365591,0.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.116183,1.0,0.493151,1.0,0.042735,0.0,0.0,0.25,1.0
1,0.161290,0.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.012448,0.0,1.000000,0.0,1.000000,0.0,0.0,1.00,1.0
2,0.430108,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.041494,1.0,0.328767,1.0,0.094017,0.0,0.0,1.00,1.0
3,0.720430,0.5,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.344398,0.0,1.000000,0.0,1.000000,0.0,0.0,1.00,1.0
4,0.720430,0.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.834025,1.0,0.301370,1.0,0.850427,0.0,0.0,0.75,1.0

independent and dependent variables

In [9]:
X=scaled_df.iloc[:,:-1]
y=scaled_df.iloc[:,-1]

splitting the data into training and testing data

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3,random_state=42)

In [11]:
X_train.shape , y_train.shape , X_test.shape , y_test.shape

((2640, 29), (2640,), (1132, 29), (1132,))

In [12]:
print("total shape is :")
scaled_df.shape

total shape is :

(3772, 30)

Training the model

In [13]:
models = {
    SVC():"SVM",
    LogisticRegression():'Logistic Regression',
    RandomForestClassifier():'Random Forest'
}

for i in models.keys():
    i.fit(X_train,y_train)

for model,name in models.items():
     print(f"Accuracy Score for {name} is : ",model.score(X_test,y_test)*100,"%")

Accuracy Score for SVM is :  92.84452296819788 %
Accuracy Score for Logistic Regression is :  95.22968197879858 %
Accuracy Score for Random Forest is :  96.64310954063605 %

In [14]:
for model,name in models.items():
    y_pred = model.predict(X_test)
    print(f"Classification Report for {name}")
    print("----------------------------------------------------------")
    print(classification_report(y_test,y_pred,zero_division=1))
    print("----------------------------------------------------------")

Classification Report for SVM
----------------------------------------------------------
              precision    recall  f1-score   support

         0.0       1.00      0.00      0.00        81
         1.0       0.93      1.00      0.96      1051

    accuracy                           0.93      1132
   macro avg       0.96      0.50      0.48      1132
weighted avg       0.93      0.93      0.89      1132

----------------------------------------------------------
Classification Report for Logistic Regression
----------------------------------------------------------
              precision    recall  f1-score   support

         0.0       0.97      0.35      0.51        81
         1.0       0.95      1.00      0.97      1051

    accuracy                           0.95      1132
   macro avg       0.96      0.67      0.74      1132
weighted avg       0.95      0.95      0.94      1132

----------------------------------------------------------
Classification Report for Random Forest
----------------------------------------------------------
              precision    recall  f1-score   support

         0.0       0.91      0.59      0.72        81
         1.0       0.97      1.00      0.98      1051

    accuracy                           0.97      1132
   macro avg       0.94      0.79      0.85      1132
weighted avg       0.96      0.97      0.96      1132

----------------------------------------------------------